[project]
name = "neetcode-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ruff>=0.12.4",
]

[dependency-groups]
dev = [
    "pyright>=1.1.403",
    "ty>=0.0.1a15",
]
